services:
  - type: web
    name: ai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ENABLE_SCHEDULER
        value: "true"
